// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class DiscoveryPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "DiscoveryPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? DiscoveryPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> DiscoveryPigeonError {
  return DiscoveryPigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsDiscoveryApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashDiscoveryApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsDiscoveryApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsDiscoveryApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsDiscoveryApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsDiscoveryApi(lhsKey, rhsKey) {
          if deepEqualsDiscoveryApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsDiscoveryApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashDiscoveryApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashDiscoveryApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashDiscoveryApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashDiscoveryApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashDiscoveryApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashDiscoveryApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Why the local network cannot be used. Both cases are the user's to fix, so
/// they are reported separately rather than as one failure.
enum DiscoveryUnavailable: Int {
  /// iOS local-network permission refused, or Android NSD unavailable.
  case permissionDenied = 0
  /// No Wi-Fi. Cellular does not count: there are no peers on it.
  case noNetwork = 1
}

/// Another device advertising Relay on the local network.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ServiceInfo: Hashable {
  /// Random per run. The only reliable way to recognise our own advertisement:
  /// the address hash is 32 bits and collides, and matching on it would make
  /// two colliding devices invisible to each other rather than merely confused.
  var instanceId: String
  /// Resolved address. Already an IP — an unresolved hostname would make the
  /// Dart side do a DNS lookup that cannot succeed on a network with no DNS.
  var host: String
  var port: Int64
  /// The mesh address the device claims. A routing hint only; the link hello
  /// and then the Noise handshake are what actually establish who is there.
  var addressHash: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ServiceInfo? {
    let instanceId = pigeonVar_list[0] as! String
    let host = pigeonVar_list[1] as! String
    let port = pigeonVar_list[2] as! Int64
    let addressHash = pigeonVar_list[3] as! Int64

    return ServiceInfo(
      instanceId: instanceId,
      host: host,
      port: port,
      addressHash: addressHash
    )
  }
  func toList() -> [Any?] {
    return [
      instanceId,
      host,
      port,
      addressHash,
    ]
  }
  static func == (lhs: ServiceInfo, rhs: ServiceInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsDiscoveryApi(lhs.instanceId, rhs.instanceId) && deepEqualsDiscoveryApi(lhs.host, rhs.host) && deepEqualsDiscoveryApi(lhs.port, rhs.port) && deepEqualsDiscoveryApi(lhs.addressHash, rhs.addressHash)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ServiceInfo")
    deepHashDiscoveryApi(value: instanceId, hasher: &hasher)
    deepHashDiscoveryApi(value: host, hasher: &hasher)
    deepHashDiscoveryApi(value: port, hasher: &hasher)
    deepHashDiscoveryApi(value: addressHash, hasher: &hasher)
  }
}

private class DiscoveryApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DiscoveryUnavailable(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return ServiceInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DiscoveryApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DiscoveryUnavailable {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ServiceInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DiscoveryApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DiscoveryApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DiscoveryApiPigeonCodecWriter(data: data)
  }
}

class DiscoveryApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DiscoveryApiPigeonCodec(readerWriter: DiscoveryApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DiscoveryHostApi {
  /// Whether discovery can run right now.
  func isAvailable() throws -> Bool
  /// Why not. Null when [isAvailable] is true.
  func unavailableReason() throws -> DiscoveryUnavailable?
  /// Publishes this device on the local network.
  ///
  /// Asynchronous because registration is confirmed by a platform callback, and
  /// reporting success before the platform has agreed would make the UI claim
  /// the device is findable when it is not.
  func advertise(instanceId: String, addressHash: Int64, port: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func stopAdvertising(completion: @escaping (Result<Void, Error>) -> Void)
  func browse(completion: @escaping (Result<Void, Error>) -> Void)
  func stopBrowsing(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DiscoveryHostApiSetup {
  static var codec: FlutterStandardMessageCodec { DiscoveryApiPigeonCodec.shared }
  /// Sets up an instance of `DiscoveryHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DiscoveryHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Whether discovery can run right now.
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
    /// Why not. Null when [isAvailable] is true.
    let unavailableReasonChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.unavailableReason\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unavailableReasonChannel.setMessageHandler { _, reply in
        do {
          let result = try api.unavailableReason()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unavailableReasonChannel.setMessageHandler(nil)
    }
    /// Publishes this device on the local network.
    ///
    /// Asynchronous because registration is confirmed by a platform callback, and
    /// reporting success before the platform has agreed would make the UI claim
    /// the device is findable when it is not.
    let advertiseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.advertise\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      advertiseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        let addressHashArg = args[1] as! Int64
        let portArg = args[2] as! Int64
        api.advertise(instanceId: instanceIdArg, addressHash: addressHashArg, port: portArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      advertiseChannel.setMessageHandler(nil)
    }
    let stopAdvertisingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.stopAdvertising\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAdvertisingChannel.setMessageHandler { _, reply in
        api.stopAdvertising { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopAdvertisingChannel.setMessageHandler(nil)
    }
    let browseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.browse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      browseChannel.setMessageHandler { _, reply in
        api.browse { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      browseChannel.setMessageHandler(nil)
    }
    let stopBrowsingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.stopBrowsing\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopBrowsingChannel.setMessageHandler { _, reply in
        api.stopBrowsing { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopBrowsingChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DiscoveryFlutterApiProtocol {
  func onServiceFound(service serviceArg: ServiceInfo, completion: @escaping (Result<Void, DiscoveryPigeonError>) -> Void)
  /// Advisory. mDNS is unreliable about departures, so this is a hint to stop
  /// dialling — never a reason to consider a peer gone. The socket closing is
  /// the authoritative signal.
  func onServiceLost(instanceId instanceIdArg: String, completion: @escaping (Result<Void, DiscoveryPigeonError>) -> Void)
  func onAvailabilityChanged(available availableArg: Bool, reason reasonArg: DiscoveryUnavailable?, completion: @escaping (Result<Void, DiscoveryPigeonError>) -> Void)
}
class DiscoveryFlutterApi: DiscoveryFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: DiscoveryApiPigeonCodec {
    return DiscoveryApiPigeonCodec.shared
  }
  func onServiceFound(service serviceArg: ServiceInfo, completion: @escaping (Result<Void, DiscoveryPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.transport_wifi.DiscoveryFlutterApi.onServiceFound\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([serviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(DiscoveryPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Advisory. mDNS is unreliable about departures, so this is a hint to stop
  /// dialling — never a reason to consider a peer gone. The socket closing is
  /// the authoritative signal.
  func onServiceLost(instanceId instanceIdArg: String, completion: @escaping (Result<Void, DiscoveryPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.transport_wifi.DiscoveryFlutterApi.onServiceLost\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([instanceIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(DiscoveryPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAvailabilityChanged(available availableArg: Bool, reason reasonArg: DiscoveryUnavailable?, completion: @escaping (Result<Void, DiscoveryPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.transport_wifi.DiscoveryFlutterApi.onAvailabilityChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([availableArg, reasonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(DiscoveryPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
