// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsBleApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashBleApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsBleApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsBleApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsBleApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsBleApi(lhsKey, rhsKey) {
          if deepEqualsBleApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsBleApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashBleApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashBleApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashBleApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashBleApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashBleApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashBleApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// A peer currently reachable over the mesh.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PeerInfo: Hashable {
  /// Stable for the duration of a session only, never across sessions.
  var peerId: String
  /// 1 means a direct radio connection.
  var hopDistance: Int64
  var isDirect: Bool
  var lastSeenMillis: Int64
  var rssi: Int64? = nil
  var nickname: String? = nil
  /// Truncated address hash this peer advertises.
  var sessionKeyHash: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PeerInfo? {
    let peerId = pigeonVar_list[0] as! String
    let hopDistance = pigeonVar_list[1] as! Int64
    let isDirect = pigeonVar_list[2] as! Bool
    let lastSeenMillis = pigeonVar_list[3] as! Int64
    let rssi: Int64? = nilOrValue(pigeonVar_list[4])
    let nickname: String? = nilOrValue(pigeonVar_list[5])
    let sessionKeyHash: Int64? = nilOrValue(pigeonVar_list[6])

    return PeerInfo(
      peerId: peerId,
      hopDistance: hopDistance,
      isDirect: isDirect,
      lastSeenMillis: lastSeenMillis,
      rssi: rssi,
      nickname: nickname,
      sessionKeyHash: sessionKeyHash
    )
  }
  func toList() -> [Any?] {
    return [
      peerId,
      hopDistance,
      isDirect,
      lastSeenMillis,
      rssi,
      nickname,
      sessionKeyHash,
    ]
  }
  static func == (lhs: PeerInfo, rhs: PeerInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsBleApi(lhs.peerId, rhs.peerId) && deepEqualsBleApi(lhs.hopDistance, rhs.hopDistance) && deepEqualsBleApi(lhs.isDirect, rhs.isDirect) && deepEqualsBleApi(lhs.lastSeenMillis, rhs.lastSeenMillis) && deepEqualsBleApi(lhs.rssi, rhs.rssi) && deepEqualsBleApi(lhs.nickname, rhs.nickname) && deepEqualsBleApi(lhs.sessionKeyHash, rhs.sessionKeyHash)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PeerInfo")
    deepHashBleApi(value: peerId, hasher: &hasher)
    deepHashBleApi(value: hopDistance, hasher: &hasher)
    deepHashBleApi(value: isDirect, hasher: &hasher)
    deepHashBleApi(value: lastSeenMillis, hasher: &hasher)
    deepHashBleApi(value: rssi, hasher: &hasher)
    deepHashBleApi(value: nickname, hasher: &hasher)
    deepHashBleApi(value: sessionKeyHash, hasher: &hasher)
  }
}

/// Current transport health. Every degraded state is surfaced, never swallowed.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TransportStatus: Hashable {
  var running: Bool
  var adapterOn: Bool
  var permissionsGranted: Bool
  var advertising: Bool
  var scanning: Bool
  var connectedPeerCount: Int64
  /// False on hardware with no BLE peripheral support. Such a device can still
  /// receive and relay, but cannot be discovered — the UI must say so.
  var canAdvertise: Bool
  /// "performance" | "balanced" | "saver"
  var powerMode: String
  var detail: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TransportStatus? {
    let running = pigeonVar_list[0] as! Bool
    let adapterOn = pigeonVar_list[1] as! Bool
    let permissionsGranted = pigeonVar_list[2] as! Bool
    let advertising = pigeonVar_list[3] as! Bool
    let scanning = pigeonVar_list[4] as! Bool
    let connectedPeerCount = pigeonVar_list[5] as! Int64
    let canAdvertise = pigeonVar_list[6] as! Bool
    let powerMode = pigeonVar_list[7] as! String
    let detail: String? = nilOrValue(pigeonVar_list[8])

    return TransportStatus(
      running: running,
      adapterOn: adapterOn,
      permissionsGranted: permissionsGranted,
      advertising: advertising,
      scanning: scanning,
      connectedPeerCount: connectedPeerCount,
      canAdvertise: canAdvertise,
      powerMode: powerMode,
      detail: detail
    )
  }
  func toList() -> [Any?] {
    return [
      running,
      adapterOn,
      permissionsGranted,
      advertising,
      scanning,
      connectedPeerCount,
      canAdvertise,
      powerMode,
      detail,
    ]
  }
  static func == (lhs: TransportStatus, rhs: TransportStatus) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsBleApi(lhs.running, rhs.running) && deepEqualsBleApi(lhs.adapterOn, rhs.adapterOn) && deepEqualsBleApi(lhs.permissionsGranted, rhs.permissionsGranted) && deepEqualsBleApi(lhs.advertising, rhs.advertising) && deepEqualsBleApi(lhs.scanning, rhs.scanning) && deepEqualsBleApi(lhs.connectedPeerCount, rhs.connectedPeerCount) && deepEqualsBleApi(lhs.canAdvertise, rhs.canAdvertise) && deepEqualsBleApi(lhs.powerMode, rhs.powerMode) && deepEqualsBleApi(lhs.detail, rhs.detail)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TransportStatus")
    deepHashBleApi(value: running, hasher: &hasher)
    deepHashBleApi(value: adapterOn, hasher: &hasher)
    deepHashBleApi(value: permissionsGranted, hasher: &hasher)
    deepHashBleApi(value: advertising, hasher: &hasher)
    deepHashBleApi(value: scanning, hasher: &hasher)
    deepHashBleApi(value: connectedPeerCount, hasher: &hasher)
    deepHashBleApi(value: canAdvertise, hasher: &hasher)
    deepHashBleApi(value: powerMode, hasher: &hasher)
    deepHashBleApi(value: detail, hasher: &hasher)
  }
}

/// Counters for the diagnostics screen. Mesh problems are otherwise invisible.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RelayStats: Hashable {
  var framesReceived: Int64
  var framesRelayed: Int64
  var framesDropped: Int64
  var framesSuppressed: Int64
  var storedForForward: Int64
  var inboxDepth: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RelayStats? {
    let framesReceived = pigeonVar_list[0] as! Int64
    let framesRelayed = pigeonVar_list[1] as! Int64
    let framesDropped = pigeonVar_list[2] as! Int64
    let framesSuppressed = pigeonVar_list[3] as! Int64
    let storedForForward = pigeonVar_list[4] as! Int64
    let inboxDepth = pigeonVar_list[5] as! Int64

    return RelayStats(
      framesReceived: framesReceived,
      framesRelayed: framesRelayed,
      framesDropped: framesDropped,
      framesSuppressed: framesSuppressed,
      storedForForward: storedForForward,
      inboxDepth: inboxDepth
    )
  }
  func toList() -> [Any?] {
    return [
      framesReceived,
      framesRelayed,
      framesDropped,
      framesSuppressed,
      storedForForward,
      inboxDepth,
    ]
  }
  static func == (lhs: RelayStats, rhs: RelayStats) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsBleApi(lhs.framesReceived, rhs.framesReceived) && deepEqualsBleApi(lhs.framesRelayed, rhs.framesRelayed) && deepEqualsBleApi(lhs.framesDropped, rhs.framesDropped) && deepEqualsBleApi(lhs.framesSuppressed, rhs.framesSuppressed) && deepEqualsBleApi(lhs.storedForForward, rhs.storedForForward) && deepEqualsBleApi(lhs.inboxDepth, rhs.inboxDepth)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RelayStats")
    deepHashBleApi(value: framesReceived, hasher: &hasher)
    deepHashBleApi(value: framesRelayed, hasher: &hasher)
    deepHashBleApi(value: framesDropped, hasher: &hasher)
    deepHashBleApi(value: framesSuppressed, hasher: &hasher)
    deepHashBleApi(value: storedForForward, hasher: &hasher)
    deepHashBleApi(value: inboxDepth, hasher: &hasher)
  }
}

private class BleApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PeerInfo.fromList(self.readValue() as! [Any?])
    case 130:
      return TransportStatus.fromList(self.readValue() as! [Any?])
    case 131:
      return RelayStats.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BleApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PeerInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? TransportStatus {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? RelayStats {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BleApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BleApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BleApiPigeonCodecWriter(data: data)
  }
}

class BleApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BleApiPigeonCodec(readerWriter: BleApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BleHostApi {
  /// Whether every runtime permission the mesh needs has been granted.
  func hasPermissions() throws -> Bool
  /// Shows the system permission dialog and resolves with the outcome.
  ///
  /// Asynchronous because the answer arrives on an activity callback, which may
  /// be many seconds later or never — the user can leave the dialog on screen.
  func requestPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  func isBluetoothEnabled() throws -> Bool
  /// Asks the OS to turn Bluetooth on. Never forces it: an app silently
  /// enabling a radio is exactly the behaviour this one exists to avoid.
  func requestEnableBluetooth() throws
  /// Starts the radio and the foreground relay.
  ///
  /// [addressHash] is this device's truncated session address; native needs it
  /// to decide which frames are terminal and must be persisted for Dart.
  func start(addressHash: Int64, powerMode: String) throws
  func stop() throws
  /// Queues a frame. [targetPeerId] null means broadcast to every peer;
  /// [excludePeerId] omits one, used so a relayed frame is never echoed back.
  func sendFrame(frame: FlutterStandardTypedData, targetPeerId: String?, excludePeerId: String?) throws
  func getPeers() throws -> [PeerInfo]
  func getStatus() throws -> TransportStatus
  func getStats() throws -> RelayStats
  /// Drains frames addressed to this device that arrived while Dart was not
  /// running. This is what makes the app-closed case work.
  func drainInbox() throws -> [FlutterStandardTypedData]
  func setPowerMode(mode: String) throws
  /// Stealth mode: stop advertising and presence, keep relaying for others.
  /// Continuing to relay is what provides cover.
  func setStealthMode(enabled: Bool) throws
  /// Sets the presence beacon contents. Empty nickname suppresses the beacon.
  func setAnnounce(nickname: String, signedSessionKey: FlutterStandardTypedData) throws
  /// Destroys all native state: inbox, store-and-forward queue, dedup table.
  /// Part of panic wipe; irreversible.
  func wipe() throws
  /// True when the OS is likely to kill the relay service. Drives the
  /// per-manufacturer battery-exemption prompt.
  func needsBatteryExemption() throws -> Bool
  func openBatterySettings() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BleHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BleApiPigeonCodec.shared }
  /// Sets up an instance of `BleHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BleHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Whether every runtime permission the mesh needs has been granted.
    let hasPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.hasPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasPermissionsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.hasPermissions()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasPermissionsChannel.setMessageHandler(nil)
    }
    /// Shows the system permission dialog and resolves with the outcome.
    ///
    /// Asynchronous because the answer arrives on an activity callback, which may
    /// be many seconds later or never — the user can leave the dialog on screen.
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { _, reply in
        api.requestPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    let isBluetoothEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.isBluetoothEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isBluetoothEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isBluetoothEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isBluetoothEnabledChannel.setMessageHandler(nil)
    }
    /// Asks the OS to turn Bluetooth on. Never forces it: an app silently
    /// enabling a radio is exactly the behaviour this one exists to avoid.
    let requestEnableBluetoothChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.requestEnableBluetooth\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestEnableBluetoothChannel.setMessageHandler { _, reply in
        do {
          try api.requestEnableBluetooth()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestEnableBluetoothChannel.setMessageHandler(nil)
    }
    /// Starts the radio and the foreground relay.
    ///
    /// [addressHash] is this device's truncated session address; native needs it
    /// to decide which frames are terminal and must be persisted for Dart.
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressHashArg = args[0] as! Int64
        let powerModeArg = args[1] as! String
        do {
          try api.start(addressHash: addressHashArg, powerMode: powerModeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Queues a frame. [targetPeerId] null means broadcast to every peer;
    /// [excludePeerId] omits one, used so a relayed frame is never echoed back.
    let sendFrameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.sendFrame\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendFrameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let frameArg = args[0] as! FlutterStandardTypedData
        let targetPeerIdArg: String? = nilOrValue(args[1])
        let excludePeerIdArg: String? = nilOrValue(args[2])
        do {
          try api.sendFrame(frame: frameArg, targetPeerId: targetPeerIdArg, excludePeerId: excludePeerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendFrameChannel.setMessageHandler(nil)
    }
    let getPeersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.getPeers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPeersChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPeers()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPeersChannel.setMessageHandler(nil)
    }
    let getStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.getStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStatusChannel.setMessageHandler(nil)
    }
    let getStatsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.getStats\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStatsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getStats()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStatsChannel.setMessageHandler(nil)
    }
    /// Drains frames addressed to this device that arrived while Dart was not
    /// running. This is what makes the app-closed case work.
    let drainInboxChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.drainInbox\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      drainInboxChannel.setMessageHandler { _, reply in
        do {
          let result = try api.drainInbox()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      drainInboxChannel.setMessageHandler(nil)
    }
    let setPowerModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.setPowerMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPowerModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modeArg = args[0] as! String
        do {
          try api.setPowerMode(mode: modeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPowerModeChannel.setMessageHandler(nil)
    }
    /// Stealth mode: stop advertising and presence, keep relaying for others.
    /// Continuing to relay is what provides cover.
    let setStealthModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.setStealthMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStealthModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setStealthMode(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setStealthModeChannel.setMessageHandler(nil)
    }
    /// Sets the presence beacon contents. Empty nickname suppresses the beacon.
    let setAnnounceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.setAnnounce\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAnnounceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nicknameArg = args[0] as! String
        let signedSessionKeyArg = args[1] as! FlutterStandardTypedData
        do {
          try api.setAnnounce(nickname: nicknameArg, signedSessionKey: signedSessionKeyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAnnounceChannel.setMessageHandler(nil)
    }
    /// Destroys all native state: inbox, store-and-forward queue, dedup table.
    /// Part of panic wipe; irreversible.
    let wipeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.wipe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      wipeChannel.setMessageHandler { _, reply in
        do {
          try api.wipe()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      wipeChannel.setMessageHandler(nil)
    }
    /// True when the OS is likely to kill the relay service. Drives the
    /// per-manufacturer battery-exemption prompt.
    let needsBatteryExemptionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.needsBatteryExemption\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      needsBatteryExemptionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.needsBatteryExemption()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      needsBatteryExemptionChannel.setMessageHandler(nil)
    }
    let openBatterySettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.transport_ble.BleHostApi.openBatterySettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openBatterySettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openBatterySettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openBatterySettingsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BleFlutterApiProtocol {
  func onFrameReceived(frame frameArg: FlutterStandardTypedData, fromPeerId fromPeerIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPeerDiscovered(peer peerArg: PeerInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPeerLost(peerId peerIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStatusChanged(status statusArg: TransportStatus, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BleFlutterApi: BleFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: BleApiPigeonCodec {
    return BleApiPigeonCodec.shared
  }
  func onFrameReceived(frame frameArg: FlutterStandardTypedData, fromPeerId fromPeerIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.transport_ble.BleFlutterApi.onFrameReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([frameArg, fromPeerIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPeerDiscovered(peer peerArg: PeerInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.transport_ble.BleFlutterApi.onPeerDiscovered\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peerArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPeerLost(peerId peerIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.transport_ble.BleFlutterApi.onPeerLost\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([peerIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStatusChanged(status statusArg: TransportStatus, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.transport_ble.BleFlutterApi.onStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
