// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.kishorek.relay.wifi

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object DiscoveryApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Why the local network cannot be used. Both cases are the user's to fix, so
 * they are reported separately rather than as one failure.
 */
enum class DiscoveryUnavailable(val raw: Int) {
  /** iOS local-network permission refused, or Android NSD unavailable. */
  PERMISSION_DENIED(0),
  /** No Wi-Fi. Cellular does not count: there are no peers on it. */
  NO_NETWORK(1);

  companion object {
    fun ofRaw(raw: Int): DiscoveryUnavailable? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Another device advertising Relay on the local network.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ServiceInfo (
  /**
   * Random per run. The only reliable way to recognise our own advertisement:
   * the address hash is 32 bits and collides, and matching on it would make
   * two colliding devices invisible to each other rather than merely confused.
   */
  val instanceId: String,
  /**
   * Resolved address. Already an IP — an unresolved hostname would make the
   * Dart side do a DNS lookup that cannot succeed on a network with no DNS.
   */
  val host: String,
  val port: Long,
  /**
   * The mesh address the device claims. A routing hint only; the link hello
   * and then the Noise handshake are what actually establish who is there.
   */
  val addressHash: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ServiceInfo {
      val instanceId = pigeonVar_list[0] as String
      val host = pigeonVar_list[1] as String
      val port = pigeonVar_list[2] as Long
      val addressHash = pigeonVar_list[3] as Long
      return ServiceInfo(instanceId, host, port, addressHash)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      instanceId,
      host,
      port,
      addressHash,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ServiceInfo
    return DiscoveryApiPigeonUtils.deepEquals(this.instanceId, other.instanceId) && DiscoveryApiPigeonUtils.deepEquals(this.host, other.host) && DiscoveryApiPigeonUtils.deepEquals(this.port, other.port) && DiscoveryApiPigeonUtils.deepEquals(this.addressHash, other.addressHash)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DiscoveryApiPigeonUtils.deepHash(this.instanceId)
    result = 31 * result + DiscoveryApiPigeonUtils.deepHash(this.host)
    result = 31 * result + DiscoveryApiPigeonUtils.deepHash(this.port)
    result = 31 * result + DiscoveryApiPigeonUtils.deepHash(this.addressHash)
    return result
  }
}
private open class DiscoveryApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DiscoveryUnavailable.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ServiceInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DiscoveryUnavailable -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ServiceInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DiscoveryHostApi {
  /** Whether discovery can run right now. */
  fun isAvailable(): Boolean
  /** Why not. Null when [isAvailable] is true. */
  fun unavailableReason(): DiscoveryUnavailable?
  /**
   * Publishes this device on the local network.
   *
   * Asynchronous because registration is confirmed by a platform callback, and
   * reporting success before the platform has agreed would make the UI claim
   * the device is findable when it is not.
   */
  fun advertise(instanceId: String, addressHash: Long, port: Long, callback: (Result<Unit>) -> Unit)
  fun stopAdvertising(callback: (Result<Unit>) -> Unit)
  fun browse(callback: (Result<Unit>) -> Unit)
  fun stopBrowsing(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by DiscoveryHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      DiscoveryApiPigeonCodec()
    }
    /** Sets up an instance of `DiscoveryHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DiscoveryHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.isAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isAvailable())
            } catch (exception: Throwable) {
              DiscoveryApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.unavailableReason$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.unavailableReason())
            } catch (exception: Throwable) {
              DiscoveryApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.advertise$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            val addressHashArg = args[1] as Long
            val portArg = args[2] as Long
            api.advertise(instanceIdArg, addressHashArg, portArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DiscoveryApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(DiscoveryApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.stopAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopAdvertising{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DiscoveryApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(DiscoveryApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.browse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.browse{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DiscoveryApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(DiscoveryApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_wifi.DiscoveryHostApi.stopBrowsing$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopBrowsing{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DiscoveryApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(DiscoveryApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class DiscoveryFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DiscoveryFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      DiscoveryApiPigeonCodec()
    }
  }
  fun onServiceFound(serviceArg: ServiceInfo, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.transport_wifi.DiscoveryFlutterApi.onServiceFound$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(serviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DiscoveryApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Advisory. mDNS is unreliable about departures, so this is a hint to stop
   * dialling — never a reason to consider a peer gone. The socket closing is
   * the authoritative signal.
   */
  fun onServiceLost(instanceIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.transport_wifi.DiscoveryFlutterApi.onServiceLost$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(instanceIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DiscoveryApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAvailabilityChanged(availableArg: Boolean, reasonArg: DiscoveryUnavailable?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.transport_wifi.DiscoveryFlutterApi.onAvailabilityChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(availableArg, reasonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DiscoveryApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
