// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.kishorek.relay.ble

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BleApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * A peer currently reachable over the mesh.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PeerInfo (
  /** Stable for the duration of a session only, never across sessions. */
  val peerId: String,
  /** 1 means a direct radio connection. */
  val hopDistance: Long,
  val isDirect: Boolean,
  val lastSeenMillis: Long,
  val rssi: Long? = null,
  val nickname: String? = null,
  /** Truncated address hash this peer advertises. */
  val sessionKeyHash: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeerInfo {
      val peerId = pigeonVar_list[0] as String
      val hopDistance = pigeonVar_list[1] as Long
      val isDirect = pigeonVar_list[2] as Boolean
      val lastSeenMillis = pigeonVar_list[3] as Long
      val rssi = pigeonVar_list[4] as Long?
      val nickname = pigeonVar_list[5] as String?
      val sessionKeyHash = pigeonVar_list[6] as Long?
      return PeerInfo(peerId, hopDistance, isDirect, lastSeenMillis, rssi, nickname, sessionKeyHash)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      peerId,
      hopDistance,
      isDirect,
      lastSeenMillis,
      rssi,
      nickname,
      sessionKeyHash,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PeerInfo
    return BleApiPigeonUtils.deepEquals(this.peerId, other.peerId) && BleApiPigeonUtils.deepEquals(this.hopDistance, other.hopDistance) && BleApiPigeonUtils.deepEquals(this.isDirect, other.isDirect) && BleApiPigeonUtils.deepEquals(this.lastSeenMillis, other.lastSeenMillis) && BleApiPigeonUtils.deepEquals(this.rssi, other.rssi) && BleApiPigeonUtils.deepEquals(this.nickname, other.nickname) && BleApiPigeonUtils.deepEquals(this.sessionKeyHash, other.sessionKeyHash)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.peerId)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.hopDistance)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.isDirect)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.lastSeenMillis)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.rssi)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.nickname)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.sessionKeyHash)
    return result
  }
}

/**
 * Current transport health. Every degraded state is surfaced, never swallowed.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TransportStatus (
  val running: Boolean,
  val adapterOn: Boolean,
  val permissionsGranted: Boolean,
  val advertising: Boolean,
  val scanning: Boolean,
  val connectedPeerCount: Long,
  /**
   * False on hardware with no BLE peripheral support. Such a device can still
   * receive and relay, but cannot be discovered — the UI must say so.
   */
  val canAdvertise: Boolean,
  /** "performance" | "balanced" | "saver" */
  val powerMode: String,
  val detail: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TransportStatus {
      val running = pigeonVar_list[0] as Boolean
      val adapterOn = pigeonVar_list[1] as Boolean
      val permissionsGranted = pigeonVar_list[2] as Boolean
      val advertising = pigeonVar_list[3] as Boolean
      val scanning = pigeonVar_list[4] as Boolean
      val connectedPeerCount = pigeonVar_list[5] as Long
      val canAdvertise = pigeonVar_list[6] as Boolean
      val powerMode = pigeonVar_list[7] as String
      val detail = pigeonVar_list[8] as String?
      return TransportStatus(running, adapterOn, permissionsGranted, advertising, scanning, connectedPeerCount, canAdvertise, powerMode, detail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      running,
      adapterOn,
      permissionsGranted,
      advertising,
      scanning,
      connectedPeerCount,
      canAdvertise,
      powerMode,
      detail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TransportStatus
    return BleApiPigeonUtils.deepEquals(this.running, other.running) && BleApiPigeonUtils.deepEquals(this.adapterOn, other.adapterOn) && BleApiPigeonUtils.deepEquals(this.permissionsGranted, other.permissionsGranted) && BleApiPigeonUtils.deepEquals(this.advertising, other.advertising) && BleApiPigeonUtils.deepEquals(this.scanning, other.scanning) && BleApiPigeonUtils.deepEquals(this.connectedPeerCount, other.connectedPeerCount) && BleApiPigeonUtils.deepEquals(this.canAdvertise, other.canAdvertise) && BleApiPigeonUtils.deepEquals(this.powerMode, other.powerMode) && BleApiPigeonUtils.deepEquals(this.detail, other.detail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.running)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.adapterOn)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.permissionsGranted)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.advertising)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.scanning)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.connectedPeerCount)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.canAdvertise)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.powerMode)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.detail)
    return result
  }
}

/**
 * Counters for the diagnostics screen. Mesh problems are otherwise invisible.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RelayStats (
  val framesReceived: Long,
  val framesRelayed: Long,
  val framesDropped: Long,
  val framesSuppressed: Long,
  val storedForForward: Long,
  val inboxDepth: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RelayStats {
      val framesReceived = pigeonVar_list[0] as Long
      val framesRelayed = pigeonVar_list[1] as Long
      val framesDropped = pigeonVar_list[2] as Long
      val framesSuppressed = pigeonVar_list[3] as Long
      val storedForForward = pigeonVar_list[4] as Long
      val inboxDepth = pigeonVar_list[5] as Long
      return RelayStats(framesReceived, framesRelayed, framesDropped, framesSuppressed, storedForForward, inboxDepth)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      framesReceived,
      framesRelayed,
      framesDropped,
      framesSuppressed,
      storedForForward,
      inboxDepth,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RelayStats
    return BleApiPigeonUtils.deepEquals(this.framesReceived, other.framesReceived) && BleApiPigeonUtils.deepEquals(this.framesRelayed, other.framesRelayed) && BleApiPigeonUtils.deepEquals(this.framesDropped, other.framesDropped) && BleApiPigeonUtils.deepEquals(this.framesSuppressed, other.framesSuppressed) && BleApiPigeonUtils.deepEquals(this.storedForForward, other.storedForForward) && BleApiPigeonUtils.deepEquals(this.inboxDepth, other.inboxDepth)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.framesReceived)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.framesRelayed)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.framesDropped)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.framesSuppressed)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.storedForForward)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.inboxDepth)
    return result
  }
}
private open class BleApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeerInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TransportStatus.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RelayStats.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PeerInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is TransportStatus -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is RelayStats -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BleHostApi {
  /** Whether every runtime permission the mesh needs has been granted. */
  fun hasPermissions(): Boolean
  /**
   * Shows the system permission dialog and resolves with the outcome.
   *
   * Asynchronous because the answer arrives on an activity callback, which may
   * be many seconds later or never — the user can leave the dialog on screen.
   */
  fun requestPermissions(callback: (Result<Boolean>) -> Unit)
  fun isBluetoothEnabled(): Boolean
  /**
   * Asks the OS to turn Bluetooth on. Never forces it: an app silently
   * enabling a radio is exactly the behaviour this one exists to avoid.
   */
  fun requestEnableBluetooth()
  /**
   * Starts the radio and the foreground relay.
   *
   * [addressHash] is this device's truncated session address; native needs it
   * to decide which frames are terminal and must be persisted for Dart.
   */
  fun start(addressHash: Long, powerMode: String)
  fun stop()
  /**
   * Queues a frame. [targetPeerId] null means broadcast to every peer;
   * [excludePeerId] omits one, used so a relayed frame is never echoed back.
   */
  fun sendFrame(frame: ByteArray, targetPeerId: String?, excludePeerId: String?)
  fun getPeers(): List<PeerInfo>
  fun getStatus(): TransportStatus
  fun getStats(): RelayStats
  /**
   * Drains frames addressed to this device that arrived while Dart was not
   * running. This is what makes the app-closed case work.
   */
  fun drainInbox(): List<ByteArray>
  fun setPowerMode(mode: String)
  /**
   * Stealth mode: stop advertising and presence, keep relaying for others.
   * Continuing to relay is what provides cover.
   */
  fun setStealthMode(enabled: Boolean)
  /** Sets the presence beacon contents. Empty nickname suppresses the beacon. */
  fun setAnnounce(nickname: String, signedSessionKey: ByteArray)
  /**
   * Destroys all native state: inbox, store-and-forward queue, dedup table.
   * Part of panic wipe; irreversible.
   */
  fun wipe()
  /**
   * True when the OS is likely to kill the relay service. Drives the
   * per-manufacturer battery-exemption prompt.
   */
  fun needsBatteryExemption(): Boolean
  fun openBatterySettings()

  companion object {
    /** The codec used by BleHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      BleApiPigeonCodec()
    }
    /** Sets up an instance of `BleHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BleHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.hasPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasPermissions())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BleApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BleApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.isBluetoothEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isBluetoothEnabled())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.requestEnableBluetooth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestEnableBluetooth()
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressHashArg = args[0] as Long
            val powerModeArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.start(addressHashArg, powerModeArg)
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.sendFrame$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val frameArg = args[0] as ByteArray
            val targetPeerIdArg = args[1] as String?
            val excludePeerIdArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.sendFrame(frameArg, targetPeerIdArg, excludePeerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.getPeers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPeers())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStatus())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.getStats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStats())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.drainInbox$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.drainInbox())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.setPowerMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setPowerMode(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.setStealthMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setStealthMode(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.setAnnounce$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nicknameArg = args[0] as String
            val signedSessionKeyArg = args[1] as ByteArray
            val wrapped: List<Any?> = try {
              api.setAnnounce(nicknameArg, signedSessionKeyArg)
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.wipe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.wipe()
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.needsBatteryExemption$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.needsBatteryExemption())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.transport_ble.BleHostApi.openBatterySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openBatterySettings()
              listOf(null)
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class BleFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by BleFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      BleApiPigeonCodec()
    }
  }
  fun onFrameReceived(frameArg: ByteArray, fromPeerIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.transport_ble.BleFlutterApi.onFrameReceived$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(frameArg, fromPeerIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BleApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPeerDiscovered(peerArg: PeerInfo, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.transport_ble.BleFlutterApi.onPeerDiscovered$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peerArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BleApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPeerLost(peerIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.transport_ble.BleFlutterApi.onPeerLost$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(peerIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BleApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onStatusChanged(statusArg: TransportStatus, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.transport_ble.BleFlutterApi.onStatusChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(BleApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
